import type { PackagesJson } from './types.js';

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatStars(stars: number | null): string {
  if (stars === null || stars === undefined) return '';
  return stars >= 1000 ? `${(stars / 1000).toFixed(1)}k` : String(stars);
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  } catch {
    return iso;
  }
}

/**
 * Generate a self-contained index.html that loads packages.json
 * and renders a searchable card grid.
 */
export function generateHtml(data: PackagesJson): string {
  const packagesJson = JSON.stringify(data).replace(/<\/script/gi, '<\\/script');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pi Package Index</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{
      font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
      background:#0d1117;color:#c9d1d9;min-height:100vh;
    }
    .header{
      border-bottom:1px solid #21262d;
      padding:1.5rem 1rem;
      max-width:960px;margin:0 auto;
    }
    .header h1{color:#f0f6fc;font-size:1.25rem;font-weight:700;margin-bottom:0.25rem}
    .header p{color:#8b949e;font-size:0.85rem}
    .search-bar{
      max-width:960px;margin:0 auto;padding:1rem;
    }
    .search-bar input{
      width:100%;
      padding:0.6rem 0.9rem;
      border-radius:6px;
      border:1px solid #30363d;
      background:#161b22;
      color:#c9d1d9;
      font-size:0.9rem;
      outline:none;
    }
    .search-bar input:focus{border-color:#58a6ff}
    .search-bar input::placeholder{color:#484f58}
    .stats{
      max-width:960px;margin:0 auto;padding:0 1rem;
      color:#8b949e;font-size:0.8rem;
    }
    .grid{
      max-width:960px;margin:0 auto;padding:1rem;
      display:grid;
      grid-template-columns:1fr;
      gap:0.75rem;
    }
    @media(min-width:640px){.grid{grid-template-columns:repeat(2,1fr)}}
    @media(min-width:960px){.grid{grid-template-columns:repeat(3,1fr)}}
    .card{
      background:#161b22;
      border:1px solid #21262d;
      border-radius:8px;
      padding:1rem;
      display:flex;
      flex-direction:column;
      gap:0.4rem;
    }
    .card-top{
      display:flex;
      align-items:center;
      gap:0.4rem;
      flex-wrap:wrap;
    }
    .card-top a{
      color:#58a6ff;
      font-size:0.95rem;
      font-weight:600;
      text-decoration:none;
      word-break:break-all;
    }
    .card-top a:hover{text-decoration:underline}
    .badge{
      font-size:0.7rem;
      padding:1px 7px;
      border-radius:9999px;
      font-weight:600;
      background:#238636;
      color:#fff;
      white-space:nowrap;
    }
    .stars{color:#e3b341;font-size:0.8rem;white-space:nowrap}
    .publisher{color:#8b949e;font-size:0.78rem}
    .keywords{display:flex;flex-wrap:wrap;gap:0.3rem}
    .tag{
      font-size:0.72rem;
      padding:2px 7px;
      border-radius:9999px;
      background:#21262d;
      color:#8b949e;
      border:1px solid #30363d;
    }
    .summary{
      color:#8b949e;font-size:0.82rem;line-height:1.45;
      display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;
    }
    .summary.expanded{display:block;-webkit-line-clamp:unset}
    .show-more{
      color:#58a6ff;font-size:0.75rem;cursor:pointer;
      background:none;border:none;padding:0;margin-top:0.1rem;
      align-self:flex-start;
    }
    .show-more:hover{text-decoration:underline}
    .meta{color:#484f58;font-size:0.72rem;margin-top:auto;padding-top:0.3rem}
    .error{color:#f85149;font-size:0.8rem}
    .empty{text-align:center;padding:3rem 1rem;color:#8b949e}
    .footer{text-align:center;padding:1.5rem 1rem;color:#484f58;font-size:0.7rem;border-top:1px solid #21262d;margin-top:1rem}
  </style>
</head>
<body>

<div class="header">
  <h1>📦 Pi Package Index</h1>
  <p>Packages tagged <code>pi-package</code> on npm</p>
</div>

<div class="search-bar">
  <input type="search" id="search" placeholder="Search packages, keywords, descriptions..." autocomplete="off">
</div>

<div class="stats" id="stats"></div>

<div class="grid" id="grid"></div>

<div class="footer">Generated by pi-package-index</div>

<script id="pkg-data" type="application/json">${packagesJson}</script>

<script>
(function(){
  const data = JSON.parse(document.getElementById('pkg-data').textContent);
  const allPackages = data.packages || [];
  const grid = document.getElementById('grid');
  const searchInput = document.getElementById('search');
  const stats = document.getElementById('stats');

  function updateStats(shown, total) {
    stats.textContent = shown === total
      ? total + ' package' + (total === 1 ? '' : 's')
      : 'Showing ' + shown + ' of ' + total + ' package' + (total === 1 ? '' : 's');
  }

  function renderCard(p) {
    const card = document.createElement('div');
    card.className = 'card';

    const top = document.createElement('div');
    top.className = 'card-top';

    const a = document.createElement('a');
    a.href = p.links.npm;
    a.target = '_blank';
    a.rel = 'noopener';
    a.textContent = p.name;
    top.appendChild(a);

    const ver = document.createElement('span');
    ver.className = 'badge';
    ver.textContent = 'v' + p.version;
    top.appendChild(ver);

    if (p.stars != null) {
      const s = document.createElement('span');
      s.className = 'stars';
      s.textContent = '★ ' + (p.stars >= 1000 ? (p.stars/1000).toFixed(1)+'k' : String(p.stars));
      top.appendChild(s);
    }

    card.appendChild(top);

    if (p.publisher) {
      const pub = document.createElement('div');
      pub.className = 'publisher';
      pub.textContent = 'by ' + p.publisher;
      card.appendChild(pub);
    }

    if (p.keywords && p.keywords.length) {
      const kw = document.createElement('div');
      kw.className = 'keywords';
      p.keywords.forEach(function(k){
        const t = document.createElement('span');
        t.className = 'tag';
        t.textContent = k;
        kw.appendChild(t);
      });
      card.appendChild(kw);
    }

    if (p.error) {
      const err = document.createElement('div');
      err.className = 'error';
      err.textContent = p.error;
      card.appendChild(err);
    } else {
      const summaryText = p.summary || p.description || '';
      if (summaryText) {
        const sum = document.createElement('div');
        sum.className = 'summary';
        sum.textContent = summaryText;
        card.appendChild(sum);

        requestAnimationFrame(function(){
          if (sum.scrollHeight > sum.clientHeight + 2) {
            const btn = document.createElement('button');
            btn.className = 'show-more';
            btn.textContent = 'Show more';
            btn.onclick = function(){
              sum.classList.toggle('expanded');
              btn.textContent = sum.classList.contains('expanded') ? 'Show less' : 'Show more';
            };
            card.appendChild(btn);
          }
        });
      }
    }

    const meta = document.createElement('div');
    meta.className = 'meta';
    try {
      meta.textContent = 'Updated ' + new Date(p.date).toLocaleDateString('en-US', {year:'numeric',month:'short',day:'numeric'});
    } catch {
      meta.textContent = p.date;
    }
    card.appendChild(meta);

    return card;
  }

  function render(packages) {
    grid.innerHTML = '';
    if (packages.length === 0) {
      grid.innerHTML = '<div class="empty">No packages match your search.</div>';
      updateStats(0, allPackages.length);
      return;
    }
    packages.forEach(function(p){
      grid.appendChild(renderCard(p));
    });
    updateStats(packages.length, allPackages.length);
  }

  function filter(term) {
    const t = term.toLowerCase().trim();
    if (!t) return allPackages;
    return allPackages.filter(function(p){
      return p.name.toLowerCase().includes(t) ||
        (p.description || '').toLowerCase().includes(t) ||
        (p.summary || '').toLowerCase().includes(t) ||
        (p.publisher || '').toLowerCase().includes(t) ||
        p.keywords.some(function(k){ return k.toLowerCase().includes(t); });
    });
  }

  let debounceTimer;
  searchInput.addEventListener('input', function(){
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(function(){
      render(filter(searchInput.value));
    }, 150);
  });

  render(allPackages);
})();
</script>
</body>
</html>`;
}
